module Objctify 

    class Templates 

        def self.header(name)
            "//
//  #{name}.h
//  #{name}
//
//
          
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
          
//! Project version number for #{name}.
FOUNDATION_EXPORT double #{name}VersionNumber;
          
//! Project version string for #{name}.
FOUNDATION_EXPORT const unsigned char #{name}VersionString[];
          
"
        end

        def self.jre_header(name)
            "//
//  #{name}_JRE_Umbrella.h
//  JRE
//
//  Wrapper of all headers from j2objc_dist/include
//  DO NOT EDIT! 
//  Generated by Objctify
          
"
        end

    end

end